### ISSUE TITLE
issue converting user fine-tuned whisper models

### ISSUE THREAD

**Issue by laphang** [OpenNMT/CTranslate2#1139]
I get the error below when trying to convert user fine-tuned whisper models on HF. eg tried with a couple different one
https://huggingface.co/katkha/whisper-small-ka/tree/main
https://huggingface.co/omar47/whisper-small-ur/tree/main

The example command used and error is below. 

It seems like config.json file for those do have a decoder_layers field, so not sure why the error is occurring. 

It worked fine with the openai whisper models. 

It would be useful to be able to convert whisper models that have been fine-tuned using the HF fine tuning scripts

```
ct2-transformers-converter --model katkha/whisper-small-ka --output_dir /root/data/transcription/model/ct2/katkha-whisper-small-ka \
    --copy_files tokenizer.json --quantization float16

Traceback (most recent call last):
  File "/opt/conda/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 863, in main
    converter.convert_from_args(args)
  File "/opt/conda/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/opt/conda/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/opt/conda/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 99, in _load
    spec = loader(model, tokenizer)
  File "/opt/conda/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 154, in __call__
    self.set_config(spec.config, model, tokenizer)
  File "/opt/conda/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 584, in set_config
    range(config.decoder_layers // 2, config.decoder_layers),
AttributeError: 'WhisperConfig' object has no attribute 'decoder_layers'

```

**Comment by guillaumekln** [comment]
This error was fixed in version 3.9.1. Can you update?

**Comment by laphang** [comment]
Thanks, yes it works with 3.9.1.
