### ISSUE TITLE
Mbart50 many to one conversion not working

### ISSUE THREAD

**Issue by Latrolage** [OpenNMT/CTranslate2#1455]
Using the "many to one" finetuned model found at https://github.com/facebookresearch/fairseq/blob/main/examples/multilingual/README.md#mbart50-models (specifically: https://dl.fbaipublicfiles.com/fairseq/models/mbart50/mbart50.ft.n1.tar.gz) I tried to follow the [instructions from ctranslate2](https://github.com/OpenNMT/CTranslate2/blob/master/docs/guides/fairseq.md#mbart-50) to convert it to a ctranslate2 usable model.

However, I get this:
<details>

```
ct2-fairseq-converter --data_dir mbart50.ft.n1/ --model_path mbart50.ft.n1/model.pt --output_dir mbart50_ct2
Traceback (most recent call last):
  File "/home/user/ai/translation/venv/bin/ct2-fairseq-converter", line 8, in <module>
    sys.exit(main())
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/fairseq.py", line 341, in main
    converter.convert_from_args(args)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/fairseq.py", line 149, in _load
    checkpoint = checkpoint_utils.load_checkpoint_to_cpu(self._model_path)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 343, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 681, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/dataclass/utils.py", line 426, in convert_namespace_to_omegaconf
    _set_legacy_defaults(cfg.model, ARCH_MODEL_REGISTRY[args.arch])
KeyError: 'denoising_large'
```
</details>

I couldn't find anything about it, so I tried https://github.com/facebookresearch/fairseq/issues/3474#issuecomment-914635353 and added `args.arch = 'mbart_large'` at the start of the `convert_namespace_to_omegaconf` function of `fairseq/dataclass/utils.py` but now I'm getting:

```
ct2-fairseq-converter --data_dir mbart50.ft.n1/ --model_path mbart50.ft.n1/model.pt --output_dir mbart50_ct2
Traceback (most recent call last):
  File "/home/user/ai/translation/venv/bin/ct2-fairseq-converter", line 8, in <module>
    sys.exit(main())
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/fairseq.py", line 341, in main
    converter.convert_from_args(args)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/ctranslate2/converters/fairseq.py", line 168, in _load
    task = fairseq.tasks.setup_task(args)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/tasks/__init__.py", line 46, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/tasks/translation_multi_simple_epoch.py", line 127, in setup_task
    langs, dicts, training = MultilingualDatasetManager.prepare(
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 370, in prepare
    language_list = cls.load_langs(args, **kargs)
  File "/home/user/ai/translation/venv/lib/python3.10/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 284, in load_langs
    if args.lang_dict and args.langs:
AttributeError: 'Namespace' object has no attribute 'langs'
```

**Comment by guillaumekln** [comment]
The converter may require an older fairseq version. I know it worked with `fairseq==0.10.2` but I'm not sure if you can install this version with Python 3.10.

Note that this model is also on the Hugging Face Hub and can be converted with `ct2-transformers-converter`:

```
ct2-transformers-converter --model facebook/mbart-large-50-many-to-one-mmt --output_dir mbart50_ct2
```

If you use the Transformers converter, you can continue using the SentencePiece model from the fairseq example, but you need to slightly change the tokenization.

Change this:

```python
source = ["[en_XX]"] + source
target_prefix = ["[ro_RO]"]
```

To this:

```python
source = ["en_XX"] + source + ["</s>"]
target_prefix = ["ro_RO"]
```

(manually add EOS + remove brackets around lang codes)
